import React from 'react'



export default function Terms () {


  return (
    <div className="article">
        <section>
            <p>UpBlockchain User Agreement (hereinafter referred to as “Agreement”) is a contract between you (“user” and collectively with others using the platform “users”) and Up Blockchain Technology Limited (https://upblockchain.io) (the Site) (“we”, “us”, “our”, and “UpBlockchain”). Terms of this Agreement affect your legal rights and obligations. If you do not agree to this Agreement, do not access or use any of our services (“UpBlockchain Services”).</p>
            <p>In the event of any violation of the Agreement, we reserve the right to suspend or terminate your access to UpBlockchain Services. We may also file a suspicious transaction report (“STR”) if we know or have reasons to believe that the user, user’s funds or assets, or transactions conducted or attempted by the user may involve potential money laundering or terrorist financing related criminal activity, regardless of the amount involved. For any user who is suspected of violating relevant laws and regulations, UpBlockchain has the right to freeze the user’s accounts and all assets, and transfer them to relevant government authorities as required by law.</p>
            <p>UpBlockchain reserves the right to change or modify the terms and conditions contained in this Agreement, including but not limited to any policy or guideline of the Site, at any time and at its sole and absloute discretion. This Agreement may be updated regularly and corresponding notices of changes will be given to users. Any changes or modifications will take effect immediately thereafter. The Agreement, as revised, updated or amended, will then replace the previous version upon being published on the Site. Users may access to the latest version of the Agreement at any time.</p>
        </section>
        <section>
            <h3>I. Contents and Release of the Agreement</h3>
            <p>1.1. The contents of this Agreement include its main body, schedules, appendices and/or annexures and all valid amendments, supplements, and announcements that UpBlockchain has released or may release from time to time, all of which constitute an integral part of this Agreement and shall have the same legal effect as the Agreement. Except as otherwise officially stated, all UpBlockchain Services are bound by the terms of this Agreement.</p>
            <p>1.2. You should carefully read all the contents of the Agreement before using UpBlockchain Services. If you have any questions regarding this Agreement or the use of the Site, please contact UpBlockchain directly by sending an email at terms@upblockchain.org Regardless of whether you have read the Agreement, by using any services made available through the UpBlockchain website at https://upblockchain.io, the UpBlockchain API, and/or any associated UpBlockchain-hosted websites or mobile applications (collectively the “Site”), you agree to be bound by this Agreement. You do not have the right to claim that the Agreement is invalid or require revocation because you have not read this Agreement or you have not received any response from UpBlockchain to your consultation.
            </p>
            <p>1.3. You are committed to accept and comply with this Agreement. UpBlockchain reserves the right to change or modify the terms and conditions contained in this Agreement. We will provide notices of these changes by posting official announcements at https://upblockchain.io. We will not inform users individually. Any changes or modifications will take effect immediately upon being published on the Site. These changes will apply at that instant to all the current and subsequent uses of the Site. If you do not agree with such changes or modifications, you should stop using UpBlockchain Services immediately. Your continued use of this Site acts as acceptance of the last revised Agreement with its updated changes and modifications.</p>
        </section>
        <section>
            <h3>II. Account</h3>
            <h4>2.1. Eligibility and Prohibition of Using our Services</h4>
            <p>​By accessing or using UpBlockchain Services, you represent and warrant that you have full capacity for civil rights and civil conduct. The users can be natural persons, legal entities or other organizations. You also represent and warrant that you are not on any terrorist organizations and terrorist activities personnel lists, such as the United Nations Security Council terrorist organizations and terrorist activities personnel list, nor restricted or prohibited from engaging in any type of trading platforms by the People’s Bank Of China (PBOC), as well as other administrative law enforcement agencies. If you do not have the above qualifications, you and your guardian shall bear all the consequences arising therefrom, and UpBlockchain reserves the rights to cancel or permanently suspend your account and claim against you and your guardian.</p>
            <h4>2.2. The Purpose of Using UpBlockchain Services</h4>
            <p>You represent and warrant that your use of UpBlockchain Services is not for the purpose of conducting any illegal or criminal activities nor for the purpose of breaching or disordering UpBlockchain’s digital assets transactions.</p>
            <h4>2.3. Wallet Security</h4>
            <p>​You are responsible for the custody and confidentiality of your digital assets wallet password, and you are responsible for all activities (including but not limited to information disclosure, posting, online click consent or submission of various requests) that occur under that login and password.</p>
            <h4>You agree to:</h4>
            <p>(1) Immediately notify UpBlockchain if any person has unauthorized use of your personal digital wallet or any other breach of confidentiality, and accept all risks of unauthorized access.</p>
            <p>(2) Ensure that you strictly comply with the Site/service security, certification, transactions, deposit, withdrawal mechanism or process.</p>
            <p>(3) Make sure you leave the Site/service in the correct way at the end of each trading period. As a decentralized exchange, UpBlockchain shall not and will not be liable for any loss whatsoever arising from your failure to comply with this Section. It is reasonable for you to understand that UpBlockchain takes action on your request but is not responsible for any consequences (including but not limited to any loss) that you have incurred before taking action.</p>
        </section>
        <section>
            <h3>III. UpBlockchain Services</h3>
            <h4>3.1. Our Services</h4>
            <p>UpBlockchain provides an online decentralized Ethereum-based tokens trading platform for users to conduct trading. We offer users with a convenient way to trade ETH and many ERC-20 tokens. https://upblockchain.io as the platform provider is not a buyer or seller in these trades. By using the Upblockchain Services, users can create trading orders, inquire blockchain asset price and trading information, conclude the transaction, and make a deal on the Site. UpBlockchain may make other ancillary services available to Users to facilitate the exchange of tokens like lending, limit orders, and stop orders. You are welcome to attend all events and activities organized by us, as well as to use other information and technical services. Our services do not provide users with the ability to trade one form of legal tender for another form of legal tender.</p>
            <h4>3.2. Rules and Acceptable Use</h4>
            <p>3.2.1. When accessing or using UpBlockchain Services, you acknowledge and consent that it is your sole responsibility to comply with applicable laws and regulations, UpBlockchain’s terms and agreements, and other relevant provisions. You agree that you will not violate any law, contract, intellectual property or other third-party right or commit a tort and that you are solely responsible for your conduct and for reporting and paying any taxes arising from your use of the Services. You acknowledge that your use of UpBlockchain will not endanger national security or disclose state secrets. You shall not violate the national community and the legitimate rights and interests of citizens. For any legal consequences caused by your violation of the terms and commitments, UpBlockchain assumes no responsibility and you shall ensure that UpBlockchain will not bear any losses.</p>
            <p>​ You understand and consent that if UpBlockchain suspects you or others of using your information in furtherance of illegal activity, UpBlockchain may be required to provide your information to government agencies as required by law.</p>
            <p>3.2.2. You agree you will not use the UpBlockchain Services in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying UpBlockchain Services, or that could damage, disable, overburden or impair the functioning of UpBlockchain Services in any manner. If a dispute happens between you and another user(s) when using the UpBlockchain Services, UpBlockchain has the right to make a judgment in its sole discretion.
            </p>
            <p>3.2.3. You agree that you will not copy, transmit, distribute, sell, resell, license, de-compile, reverse engineer, disassemble, modify, publish, participate in the transfer or sale of, create derivative works from, perform, display, incorporate into another website, or in any other way exploit any of the content or any other part of the UpBlockchain Services or any derivative works thereof, in whole or in part for commercial or non-commercial purposes. Without limiting the foregoing, you will not frame or display the Site or its contents as part of other web site or any other work of authorship without the prior written permission of UpBlockchain. In addition, you will not use any devices, software, callable routines, web crawler, scraper or other automated means or interface not provided by us to access and intervene our Services or to extract data. It is also prohibited for you to take any action that imposes an unreasonable or disproportionately large load on our infrastructure, or detrimentally interfere with, intercept, or expropriate any system, data, or information.</p>
            <p>3.2.4. You acknowledge and consent that UpBlockchain has the right to determine whether you have violated any of these terms in the Agreement, in our sole discretion. We may terminate your access to the UpBlockchain Services based our sole discretion, immediately and without prior notice. If UpBlockchain suspects your use of the UpBlockchain Services involves illegal activity according to law or any regulatory terms, we have the right to publicize the detail of your violations, as well as the measures adopted by us.</p>
            <p>3.2.5. UpBlockchain reserves the right to determine whether your use of the UpBlockchain Services (include any direct and indirect effects that may have happened as the result of your previous action), has violated any terms of the Agreement. You agree to indemnify, defend and hold UpBlockchain , its affiliates and service providers, and each of their respective officers, directors, agents, employees, and representatives, harmless from any claim or demand (including attorneys’ fees and costs and any fines, fees or penalties imposed by any regulatory authority) arising out of or related to: (a) your breach of the terms of this Agreement, (b) your use of the UpBlockchain Services, or (c) your violation of any law, rule, or regulation, or the rights of any third party.</p>
            <p>3.3. Change of Service, Suspension, Termination - When special circumstances arise, UpBlockchain reserves the rights to revise the contents of UpBlockchain Services and may suspend or terminate the UpBlockchain Services so provided.</p>
            <p>3.3.1. Change of Service - We reserve the right to revise the contents of UpBlockchain Services and other policies and announcements published by UpBlockchain, at any time and in our sole discretion. We will update our Agreement regularly and provide notice of these changes on https://upblockchain.io. Any changes or modifications will be effective immediately when the revision is posted. Your continued use of this Site acts as your acceptance of such changes or modifications. If you do not agree to the terms in effect when you access or use the Site, you must stop using the Site and all UpBlockchain Services. We encourage you to review the Agreement frequently to ensure you understand the terms and conditions that apply to your access to, and use of, the UpBlockchain Services.</p>
            <p>3.3.2. Suspension and Termination - UpBlockchain reserves the right to terminate all UpBlockchain Services in accordance with this Agreement. This Agreement will expire when all UpBlockchain Services are terminated. After the expiration of this Agreement, UpBlockchain is no longer obligated to deliver any processed or unprocessed information or the user(s) or any other third parties. You also have no right to request UpBlockchain to provide any services or to fulfill any obligations. If you breach any of the terms, you will continue to be held responsible and accountable after the Agreement expires.</p>
        </section>
        <section>
            <h3>IV. Trading Rules</h3>
            <p>You acknowledge and agree that by accessing and using UpBlockchain Services, you comply with all terms mentioned in the Agreement when making any transactions or orders, including but not limited to review exchange information; make deposits and withdrawals; submit an order; check transactions, and cancel an order. You also agree to follow UpBlockchain’s digital asset trading rules:</p>
            <p>4.1 Browsing transaction information: When you browse the digital asset transaction information on UpBlockchain, you should carefully read all the contents contained in the transaction information before trading, including but not limited to the digital asset price, commission and fees.</p>
            <p>4.2 Transfer and Approve: you understand and agree that although UpBlockchain does not charge any transfer or approve fees, it is your responsibility to cover the gas fee (Ethereum network fee). This is for the cost of executing transactions on the Ethereum network. These transaction fees will be deducted from your wallet.</p>
            <p>4.3. Transaction records: You can view your corresponding transaction records in your trading history.</p>
        </section>
        <section>
            <h3>V. User Rights and Licences</h3>
            <p>UpBlockchain grants you a limited, non-exclusive, non-transferable licence, subject to the terms of this Agreement, to access and use the UpBlockchain website and the UpBlockchain Services, solely for approved purposes as permitted by UpBlockchain. Any other use of the UpBlockchain Services or any contents therein is expressly prohibited. All other rights in the Site or its contents are reserved by us. You agree you will not copy, transmit, distribute, sell, licence, reverse engineer, modify, publish, or participate in the transfer or sale of, create derivative works from, or in any other way exploit any of the UpBlockchain’s contents.</p>
            <p>5.1 You have the right to obtain the blockchain asset information from UpBlockchain. UpBlockchain and its users may provide third party contents on the Site. UpBlockchain does not control, endorse, or adopt any third party contents and makes no representation or warranties of any kind regarding the third party contents, including but not limited to its accuracy or completeness. You acknowledge and consent that UpBlockchain is not responsible or liable in any manner for any third party contents and undertakes no responsibility to update or review any third party contents. You acknowledge and consent that your use of such third party contents is at your own risk. Your business dealings or correspondence with, or participation in promotions of, any third parties, and any terms, conditions, warranties, or representations associated with such dealings or promotions, are solely between you and such third parties. We are not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or promotions or as the result of the presence of such third party contents on the Site.</p>
            <p>5.2. If you encounter any technical difficulty on our platform, you can submit a ticket in the Help Center under “Support”. Our customer service team will assist you as soon as possible. Please understand that it might take some time to solve your problem. For other personal reasons due to improper use, we will not guarantee to help you recover your assets.</p>
            <p>5.3. Unless otherwise specified, UpBlockchain shall not guarantee the accuracy, completeness, reliability of any contents, including but not limited to, advertising from the Site in any manner from the UpBlockchain is not responsible for any products, services, information or materials purchased or obtained by the user according to the content information on this website. The user bears the risk of using the content of this website.</p>
            <p>5.4 You have the right to make comments and suggestions in regard to UpBlockchain services, and UpBlockchain will take your suggestions into serious consideration. If your feedback is involved with violent words, insulting verbal abuse, rumors, and defamation, once discovered, UpBlockchain has the right to clarify the relevant false text and we retain the right to further pursue legal action.</p>
            <p>5.5 You may not use the trademarks, emblems and service marks contained in this website in any way without the prior written consent of UpBlockchain, and you may not copy, reproduce, and store the information and materials contained in UpBlockchain in the retrieval system, Transmit, distribute or carry out other infringement. Please strictly abide by the relevant laws and regulations, do not publish any illegal content on UpBlockchain.</p>
            <p>5.6. A third party authorized by UpBlockchain or a third party that you agree with UpBlockchain shall have the right to accept your dispute with another user for any transaction based on your irrevocable authorization and to have sole discretion to determine the facts relating to the dispute, and then make a decision to deal with, including but not limited to adjust the transaction status of the relevant order, direct the third party to pay the company or customer service will be all or part of the payment to the transaction party or both. You should make up for the loss of UpBlockchain and its affiliates, otherwise, UpBlockchain and its affiliates reserve the rights to directly offset your interest in other contracts and to continue to recover. You understand and agree that a third party authorized by UpBlockchain or a third party that you agree to with UpBlockchain is not a judicial authority and can only identify the evidence as an ordinary person, or a third party authorized by UpBlockchain or UpBlockchain or you agree with UpBlockchain third party to the dispute is entirely based on your irrevocable mediation, it cannot guarantee that the outcome of the dispute in line with your expectations, nor on the dispute mediation conclusions bear any responsibility.</p>
        </section>
        <section>
            <h3>VI. Limitation of Liability and Disclaimer</h3>
            <p>You acknowledge and consent that you agree not to hold UpBlockchain accountable for any related losses resulted from the following circumstances (including but not limited to), whether or not such loss or damage can be reasonably foreseen by UpBlockchain and whether or not UpBlockchain has previously been advised of the possibility of such loss or damage:</p>
            <p>6.1. UpBlockchain suspects your transaction relates to a prohibited use as stated in the terms pf this Agreement.</p>
            <p>6.2. UpBlockchain suspects your transaction involves money laundering, terrorist financing, fraud, or any other type of crime.</p>
            <p>6.3. Your misunderstanding of UpBlockchain Services.</p>
            <p>6.4. UpBlockchain, as an “online service provider”, does not guarantee that the information and the UpBlockchain Services can fully meet the needs of users. UpBlockchain does not assume legal liability for errors, insults, defamation, omission, obscenity, pornography, or blasphemy that our users may encounter while using UpBlockchain Services.</p>
            <p>6.4.1. Based on the special nature of the Internet, UpBlockchain does not guarantee that the UpBlockchain Services will not be interrupted, and the timeliness of the UpBlockchain Services and the security thereof are also not guaranteed, and UpBlockchain does not bear the responsibility which is not caused by us.</p>
            <p>6.4.2. UpBlockchain may provide some links to other sites. These links are only for your convenience and learning purposes, UpBlockchain does not guarantee the authenticity, effectiveness, legitimacy of such sites.</p>
            <p>6.4.3. UpBlockchain strives to enable users to securely access and use our Site; however, we do not guarantee that the Site or its servers are free of viruses or other potentially harmful factors. Hence, the user should use the industry’s recognized software to check and kill any virus in the files downloaded from UpBlockchain.</p>
            <p>6.5. UpBlockchain is not responsible for any damage incurred during your transaction, including but not limited to profit or loss on your business activities, business interruption, loss due to the market violation, data loss, loss of reputation or goodwill.</p>
            <p>6.6. UpBlockchain shall not be liable for (a) any inaccuracy, error, delay in, or omission of (i) any information, or (ii) the transmission or delivery of information; or (b) any loss or damage arising from any event beyond our reasonable control, including but not limited to flood, extraordinary weather conditions, earthquake, or other act of God, fire, war, insurrection, riot, labor dispute, accident, action of government, communications, power failure, or equipment or software malfunction, or any other cause beyond our reasonable control.</p>
            <p>6.7. All UpBlockchain announcements and notifications will be delivered through a formal page announcement on https://upblockchain.org or https://upblockchain.io. UpBlockchain assumes no legal responsibility for any winning, discount activities or information which are delivered not by above channels.</p>
            <p>6.8. UpBlockchain aims to ensure that the platform operates 7*24 hours. But we cannot guarantee the DDoS attack, the server vendor to suspend the service, the network provider to suspend service or other force majeure events and other unknown reasons which may cause the Site cannot be accessed, the trading hall cannot be a single order, withdrawal orders, pending orders have not been a normal transaction, recharge to mention a long time not credited to the account and so on. For the above reasons resulting in loss of user assets, UpBlockchain does not assume any responsibility.</p>
            <p>6.9. The guarantees and undertakings of UpBlockchain as set forth in this Agreement are the sole warranties and representations made by UpBlockchain in respect of the services provided by this Agreement. All such warranties and representations represent the commitment and warranty of UpBlockchain itself and do not guarantee that any third party will comply with the warranties and undertakings in this Agreement. UpBlockchain does not waive any rights not covered by this Agreement to the extent that the law applies to UpBlockchain, which reserves the rights to waive or cancel the liability of UpBlockchain damage.</p>
        </section>
    </div>
  )
}
